Repository KamandPrompt/baat-cheet, pull requests merged in 2020-10, with the labels that each got.

#63 Close sidebar when clicked outside sidebar
  public/script.js
Labels: size: M

#77 Improved sidebar UX
  public/script.js
Labels: size: S

#70 Adding responsive web page with bootstrap 4
  public/client.js
  public/style.css
  views/footer_imports.ejs
  views/head_imports.ejs
  views/index.ejs
  views/user.ejs
Labels: size: XL

#83 Increased font size in add lobby page
  public/style.css
Labels: size: S

#87 Make entry page responsive using Bootstrap
  public/client.js
  public/style.css
  views/footer_imports.ejs
  views/head_imports.ejs
  views/index.ejs
  views/user.ejs
Labels: size: XL

#91 fix menu disappear after resizing window
  public/script.js
  public/style.css
Labels: size: S

#88 Message Input bar not visible in Rooms
  public/client.js
  public/script.js
  views/index.ejs
Labels: size: XL

#90 Show notification if new message comes to any room
  public/client.js
Labels: size: S

#95 style entry page
  public/script.js
  public/style.css
  views/user.ejs
Labels: size: L

#100 Send emojis is not working Lobby
  views/index.ejs
Labels: size: XS

#104 bug fix: fixes #61
  public/style.css
Labels: bug, size: XS

#107 styling all colors using bootstrap's classes
  public/client.js
  public/script.js
  public/style.css
  views/index.ejs
  views/user.ejs
Labels: size: M

#114 fix #108
  public/client.js
Labels: bug, hacktoberfest, newcomer, size: XS

#120 cleaning css
  public/client.js
  public/style.css
  views/user.ejs
Labels: size: M

#122 Added MIT License
  LICENSE
Labels: size: S

#115 Styled the message bubble with Bootstrap
  public/client.js
  public/style.css
Labels: size: L

#129 Add a Gitter chat badge to README.md
  README.md
Labels: size: S

#128 Fix number of characters in room name and description
  app.js
Labels: size: S

#130 Using Bootstrap toast for notifications, updated Bootstrap version to …
  package.json
  public/client.js
  public/notify.min.js
  public/script.js
  public/style.css
  views/footer_imports.ejs
  views/head_imports.ejs
  views/index.ejs
Labels: size: L

#135 Fixes modal closing on Enter key when creating new room
  public/script.js
  views/index.ejs
Labels: size: S

#145 Clean imports
  views/footer_imports.ejs
  views/head_imports.ejs
Labels: size: S

#147 Shifted all emoji data in a json file
  public/client.js
  public/emoji.json
  public/emojify.js
  views/footer_imports.ejs
Labels: size: M

#151 Added format rules
  .editorconfig
  CONTRIBUTING.md
Labels: size: M

#148 Adding welcome bot, and refactoring some messy things
  app.js
  public/client.js
  public/script.js
  public/utils.js
  views/footer_imports.ejs
Labels: size: XL

#146 Initial tests to verify a new connection
  app.js
  package.json
  public/client.js
  tests/app.test.js
Labels: size: XL

#158 Use shift + enter for newlines, and Enter to send msg
  public/script.js
Labels: size: S

#160 Adds the warning about losing chat history to the welcome bot
  public/client.js
Labels: size: XS

#152 feat(date format): Update date format in message; timestamp near user…
  public/client.js
  public/script.js
Labels: size: M

#139 Added touch swipe to side bar
  public/script.js
  views/footer_imports.ejs
  views/index.ejs
Labels: has conflicts, size: M
